'use client';
import {useCallback,useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import Facturacion from './facturacion';
import Recetas from './recetas';
import {consumption} from '@/lib/recipes';
import {LayoutDashboard,Package,ShoppingBag,Truck,ClipboardList,Building2,Users,ChartColumn,Plus,Printer,RefreshCw,Download} from 'lucide-react';
type Row={id:number;kind:string;data:any;version:number;creator:string;created:string};
type Field={key:string;label:string;type?:string;options?:[string,string][];required?:boolean;step?:string;min?:number;wide?:boolean};
const nav=[['Resumen',LayoutDashboard],['Compras',ShoppingBag],['Stock',Package],['Platos y recetas',ClipboardList],['Pedidos',ClipboardList],['Reparto',Truck],['Empresas y proveedores',Building2],['Cierre semanal',ChartColumn],['Cuentas por cobrar',ShoppingBag],['Equipo',Users]] as const;
const roles:Record<string,string>={admin:'Administración',cocina:'Cocina',bachero:'Bachero',caja:'Caja y postres',delivery:'Delivery'};
const categories=['Comida','Pasteleria','Condimentos','Verduleria','Limpieza','Descartables','Bebidas','Individuales','OTROS'];
const units=['unidad','kg','litro','paquete','caja'];
const pairs=(a:string[]):[string,string][]=>a.map(x=>[x,x]);
const money=(n:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(n/100);
const fmt=(d:string)=>d?.split('-').reverse().join('/')||'—';
const addDays=(d:string,n:number)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const monday=(d:string)=>addDays(d,-((new Date(d+'T12:00:00Z').getUTCDay()+6)%7));
const sum=(r:Row[],key:string)=>r.reduce((a,x)=>a+Number(x.data[key]||0),0);
const status=(r:Row)=>r.data.confirmation==='pending'?'Pendiente de confirmar':r.data.paid===r.data.total?'Pagado':r.data.paid>0?'Pago parcial':'Adeudado';
function Empty({title,description}:{title:string;description:string}){return <div className="empty"><ClipboardList size={32}/><h3>{title}</h3><p>{description}</p></div>}
function DataTable({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="table-wrap"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></div>}
function FieldInput({field,value,change}:{field:Field;value:any;change:(v:string)=>void}){return <label className={'field'+(field.wide?' wide':'')}><span>{field.label}{field.required!==false?' *':''}</span>{field.options?<Select value={String(value||'')} onValueChange={change}><SelectTrigger aria-label={field.label}><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent>{field.options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>:field.type==='textarea'?<textarea value={value||''} onChange={e=>change(e.target.value)} required={field.required!==false}/>:<input type={field.type||'text'} value={value??''} onChange={e=>change(e.target.value)} step={field.step} min={field.min} maxLength={field.type==='text'?200:undefined} required={field.required!==false}/>}</label>}
function NavigationButton({name,Icon,view,onClick}:{name:string;Icon:any;view:string;onClick:()=>void}){return <SidebarMenuItem><SidebarMenuButton isActive={view===name} onClick={onClick}><Icon/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>}
export default function Gestion(){
 const [view,setView]=useState('Resumen'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[today,setToday]=useState('2026-10-01'),[week,setWeek]=useState('2026-09-28');
 const [modal,setModal]=useState<{title:string;fields:Field[];note?:string}|null>(null),[form,setForm]=useState<any>({}),[saving,setSaving]=useState(false),[print,setPrint]=useState<any>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/gestion',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setToday(d.today);setWeek(w=>w==='2026-09-28'?monday(d.today):w);setError('');}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setPrint(null)},[view]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'consultar_gestion_viandas',description:'Lee los registros visibles para el rol actual: compras, stock y pedidos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No se admiten parámetros.');const response=await fetch('/api/gestion',{cache:'no-store'});const result:any=await response.json();if(!response.ok)throw new Error(result.error);setData(result);return result;}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 const records:Row[]=data?.records||[],of=(kind:string)=>records.filter(r=>r.kind===kind),products=of('product'),suppliers=of('supplier'),companies=of('company'),purchases=of('purchase'),orders=of('order'),movements=of('movement');
 const role=data?.user.role||'admin',financial=['admin','caja'].includes(role),manage=financial,productRoles=role!=='delivery';
 const allowed=role==='admin'?nav.map(x=>x[0]):role==='caja'?nav.filter(x=>x[0]!=='Equipo').map(x=>x[0]):role==='delivery'?['Pedidos','Reparto']:role==='bachero'?['Stock','Compras']:['Pedidos','Stock','Compras','Platos y recetas'];
 useEffect(()=>{if(data&&!allowed.includes(view))setView(allowed[0])},[data,view]);
 const stock=(p:Row)=>purchases.filter(x=>x.data.productId===p.id&&x.data.confirmation==='confirmed').reduce((a,x)=>a+x.data.quantity,0)+movements.filter(x=>x.data.productId===p.id).reduce((a,x)=>a+x.data.quantity,0);
 const weekEnd=addDays(week,6),inWeek=(d:string)=>d>=week&&d<=weekEnd,weekOrders=orders.filter(r=>inWeek(r.data.date)&&r.data.status!=='cancelado'),weekPurchases=purchases.filter(r=>inWeek(r.data.date)),confirmedWeek=weekPurchases.filter(r=>r.data.confirmation==='confirmed');
 const weekPayments=purchases.flatMap(r=>r.data.payments||[]).filter(p=>inWeek(p.date)).reduce((a,p)=>a+p.amount,0),debt=purchases.filter(r=>r.data.confirmation==='confirmed').reduce((a,r)=>a+r.data.total-r.data.paid,0),todaysOrders=orders.filter(r=>r.data.date===today&&r.data.status!=='cancelado');
 const option=(r:Row[]):[string,string][]=>r.map(x=>[String(x.id),x.data.name]);
 async function mutate(b:any){const response=await fetch('/api/gestion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const result:any=await response.json();if(!response.ok)throw new Error(result.error);return result;}
 async function action(b:any){setSaving(true);try{await mutate(b);await load();toast.success('Registro guardado');}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}
 function open(title:string,action:string,fields:Field[],defaults:any={},note?:string){setForm({action,date:today,...defaults});setModal({title,fields,note});}
 const num=(key:string,label:string,min=0,step='1'):Field=>({key,label,type:'number',min,step});
 const dateField:Field={key:'date',label:'Fecha',type:'date'};
 const notes:Field={key:'note',label:'Observaciones',type:'textarea',required:false,wide:true};
 function purchaseForm(){if(!suppliers.length){toast.info('Primero registrá un proveedor desde Empresas y proveedores.');return}if(!products.some(p=>p.data.unitConfirmed)){toast.info('Primero confirmá la unidad de un producto en Stock.');setView('Stock');return}open('Ingresar mercadería','purchase',[dateField,{key:'supplierId',label:'Proveedor',options:option(suppliers)},{key:'productId',label:'Producto',options:products.filter(p=>p.data.unitConfirmed).map(p=>[String(p.id),p.data.name+' · '+p.data.unit])},num('quantity','Cantidad',.001,'.001'),num('unitPrice','Precio por unidad ($)',0,'.01'),{key:'confirmation',label:'Confirmación',options:[['confirmed','Compra confirmada'],['pending','Pendiente de confirmar']]},num('paid','Monto pagado ($)',0,'.01'),{key:'invoice',label:'Número de comprobante',required:false},notes],{confirmation:'confirmed',quantity:1,paid:0,unitPrice:0},'El precio queda guardado en esta compra. Una compra pendiente no suma stock ni deuda hasta confirmarla.');}
 function orderForm(r?:Row){if(!companies.length){toast.info('Primero registrá una empresa.');setView('Empresas y proveedores');return}open(r?'Modificar pedido':'Nuevo pedido','order',[dateField,{key:'companyId',label:'Empresa',options:option(companies)},{key:'menu',label:'Menú',wide:true},{key:'recipeId',label:'Receta del plato',options:[['0','Sin receta · consumo manual'],...of('recipe').filter(r=>r.data.type==='plato').map(r=>[String(r.id),r.data.name] as [string,string])]},{key:'dessertRecipeId',label:'Receta del postre',options:[['0','Sin receta · consumo manual'],...of('recipe').filter(r=>r.data.type==='postre').map(r=>[String(r.id),r.data.name] as [string,string])]},num('quantity','Viandas',1),num('desserts','Postres'),notes],r?{...r.data,recipeId:String(r.data.recipeId||0),dessertRecipeId:String(r.data.dessertRecipeId||0),id:r.id}:{quantity:1,desserts:0,recipeId:'0',dessertRecipeId:'0'});}
 function entityForm(kind:string){open(kind==='company'?'Registrar empresa':'Registrar proveedor',kind,[{key:'name',label:'Nombre',wide:true},{key:'contact',label:'Contacto',required:false},{key:'address',label:'Dirección',required:false}]);}
 function productForm(){open('Nuevo ítem','product',[{key:'name',label:'Producto',wide:true},{key:'category',label:'Categoría',options:pairs(role==='bachero'?['Limpieza']:role==='cocina'?categories.filter(x=>!['Limpieza','Pasteleria'].includes(x)):categories)},{key:'unit',label:'Unidad de registro',options:pairs(units)}],{category:role==='bachero'?'Limpieza':'Comida',unit:'unidad'});}
 function movementForm(p:Row){open('Registrar movimiento de stock','movement',[dateField,num('quantity','Cantidad (+ ingreso / − consumo)',-1000000,'.001'),{key:'reason',label:'Motivo',wide:true}],{productId:p.id,quantity:''},p.data.name+' · '+p.data.unit+'. Usá valores negativos para consumos o pérdidas. El stock inicial debe cargarse luego del conteo físico.');}
 function progress(r:Row,status:string){const d=r.data,fields:Field[]=[num('quantity',status==='preparado'?'Viandas preparadas':status==='enviado'?'Viandas a enviar':'Viandas recibidas'),num('desserts',status==='preparado'?'Postres preparados':status==='enviado'?'Postres a enviar':'Postres recibidos')];if(status==='enviado')fields.push({key:'driver',label:'Repartidor',wide:true});if(status==='entregado')fields.push({key:'receiver',label:'Recibió',wide:true},notes);open(status==='preparado'?'Confirmar preparación':status==='enviado'?'Confirmar despacho':'Registrar entrega','progress',fields,{id:r.id,status,quantity:status==='preparado'?d.quantity:status==='enviado'?d.prepared:d.sent,desserts:status==='preparado'?d.desserts:status==='enviado'?d.preparedDesserts:d.sentDesserts,driver:data.user.name},d.company+' · '+fmt(d.date));}
 function preparationPreview(){const order=orders.find(r=>r.id===form.id);if(!order)return [];const ingredients=[...(order.data.recipe?consumption(order.data.recipe,Number(form.quantity||0)):[]),...(order.data.dessertRecipe?consumption(order.data.dessertRecipe,Number(form.desserts||0)):[])].filter(i=>i.quantity>0);const grouped=new Map<number,any>();for(const i of ingredients){const old=grouped.get(i.productId);grouped.set(i.productId,{...i,quantity:Number((i.quantity+(old?.quantity||0)).toFixed(6))});}return [...grouped.values()];}
 function doPrint(payload:any){setPrint(payload);setTimeout(()=>window.print(),150)}
 function downloadCSV(){const table=[['Empresa','Pedidas','Preparadas','Enviadas','Entregadas','Postres entregados'],...companies.map(c=>{const rr=weekOrders.filter(o=>o.data.companyId===c.id);return [c.data.name,sum(rr,'quantity'),sum(rr,'prepared'),sum(rr,'sent'),sum(rr,'delivered'),sum(rr,'deliveredDesserts')]}),[],['Desde',week,'Hasta',weekEnd],['Compras confirmadas',confirmedWeek.reduce((a,r)=>a+r.data.total,0)/100],['Pagos realizados',weekPayments/100],['Deuda total a la fecha',debt/100]];const csv=table.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='cierre-bondi-'+week+'.csv';a.click();URL.revokeObjectURL(url);}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{await mutate(form);setModal(null);await load();toast.success('Registro guardado');}catch(e:any){toast.error(e.message)}finally{setSaving(false)}}
 const filtered=(r:Row[])=>r.filter(x=>JSON.stringify(x.data).toLowerCase().includes(query.toLowerCase()));
 function orderTable(list:Row[]){return list.length?<DataTable headers={['Empresa / fecha','Menú','Viandas / postres','Estado','Acciones']}>{list.map(r=><TableRow key={r.id}><TableCell><b>{r.data.company}</b><small>{fmt(r.data.date)} · Pedido #{r.id}</small></TableCell><TableCell>{r.data.menu}<small>{r.data.note}</small><small>{r.data.recipe?'Receta: '+r.data.recipe.name:'Sin receta de plato · consumo manual'}</small></TableCell><TableCell>{r.data.quantity} / {r.data.desserts}<small>Preparadas: {r.data.prepared} · Enviadas: {r.data.sent}<br/>Recibidas: {r.data.delivered}</small></TableCell><TableCell><span className={'tag '+(r.data.status==='entregado'?'green':'yellow')}>{r.data.status}</span></TableCell><TableCell><div className="table-actions">{r.data.status==='pedido'&&manage&&<button className="secondary" onClick={()=>orderForm(r)}>Modificar</button>}{r.data.status==='pedido'&&['admin','caja','cocina'].includes(role)&&<button className="secondary" onClick={()=>progress(r,'preparado')}>Preparar</button>}{r.data.status==='preparado'&&['admin','caja','delivery'].includes(role)&&<button className="primary" onClick={()=>progress(r,'enviado')}>Despachar</button>}{r.data.status==='enviado'&&['admin','delivery'].includes(role)&&<button className="primary" onClick={()=>progress(r,'entregado')}>Registrar entrega</button>}{['enviado','entregado'].includes(r.data.status)&&<button className="secondary" onClick={()=>doPrint({type:'remito',order:r})}><Printer size={15}/>Remito</button>}{r.data.status==='pedido'&&manage&&<button className="secondary" onClick={()=>open('Cancelar pedido','progress',[],{id:r.id,status:'cancelado'},'El pedido quedará cancelado y se excluirá del cierre semanal.')}>Cancelar</button>}</div></TableCell></TableRow>)}</DataTable>:<Empty title="No hay pedidos" description="Los pedidos se cargan con las cantidades que solicita cada empresa."/>}
 return <><Toaster theme="dark" position="top-center"/><SidebarProvider><Sidebar className="bondi-sidebar"><SidebarHeader><img className="logo" src="/logo.png" alt="La Cocina del Bondi"/><p className="nav-label">GESTIÓN DEL NEGOCIO</p></SidebarHeader><SidebarContent><SidebarMenu>{nav.filter(([name])=>allowed.includes(name)).map(([name,Icon])=><NavigationButton key={name} name={name} Icon={Icon} view={view} onClick={()=>{setView(name);setQuery('')}}/>)}</SidebarMenu></SidebarContent><SidebarFooter><span className="role-chip">{roles[role]}</span><small>{data?.user.name||'La Cocina del Bondi'}</small></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><SidebarTrigger/><span>OPERACIÓN DIARIA</span><span className="brand-mini">EL BONDI</span></header><div className="page-heading"><div><p className="eyebrow">LA COCINA DEL BONDI · {fmt(today)}</p><h1>{view}</h1></div><div className="table-actions"><button className="secondary" onClick={load} disabled={loading} aria-label="Actualizar"><RefreshCw size={18}/></button>{data&&view==='Compras'&&productRoles&&<button className="secondary" onClick={productForm}><Plus size={18}/>Nuevo ítem</button>}{data&&((view==='Pedidos'||view==='Resumen')&&manage?<button className="primary" onClick={()=>orderForm()}><Plus size={18}/>Nuevo pedido</button>:view==='Compras'&&productRoles?<button className="primary" onClick={purchaseForm}><Plus size={18}/>Ingresar mercadería</button>:view==='Stock'&&productRoles?<button className="primary" onClick={productForm}><Plus size={18}/>Nuevo ítem</button>:null)}</div></div>
 {error?<div className="notice error"><p>{error}</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Iniciar sesión</a></div>:loading&&!data?<div className="notice">Cargando registros…</div>:data&&<>
 {view==='Resumen'&&<><div className="metrics"><article><span>Viandas pedidas hoy</span><strong>{sum(todaysOrders,'quantity')}</strong><small>{todaysOrders.length} pedidos</small></article><article><span>Compras de la semana</span><strong>{money(confirmedWeek.reduce((a,r)=>a+r.data.total,0))}</strong><small>Compras confirmadas</small></article><article><span>Saldo con proveedores</span><strong>{money(debt)}</strong><small>Saldo acumulado a la fecha</small></article><article><span>Entregas pendientes hoy</span><strong>{todaysOrders.filter(r=>!['entregado','cancelado'].includes(r.data.status)).length}</strong><small>Pedidos por completar</small></article></div><div className="notice"><span><b>Adeudado por empresas: {money(of('invoice').reduce((a,r)=>a+r.data.total-r.data.paid,0))}</b> · Cobro a mes vencido</span><button className="secondary" onClick={()=>setView('Cuentas por cobrar')}>Ver cuentas por cobrar</button></div>{!products.length&&role==='admin'&&<div className="notice"><div><b>Tu catálogo del depósito</b><p>Incorporá los productos del Excel. Después confirmá las unidades y el stock físico.</p></div><button className="primary" disabled={saving} onClick={()=>action({action:'importCatalog'})}>Incorporar catálogo</button></div>}<section className="panel"><div className="panel-heading"><h2>Pedidos de hoy</h2><span className="tag">{fmt(today)}</span></div>{orderTable(todaysOrders)}</section><div className="columns"><section className="panel"><div className="panel-heading"><h2>Compras por resolver</h2></div><div className="summary-line"><span>Pendientes de confirmar</span><b>{purchases.filter(r=>r.data.confirmation==='pending').length}</b></div><div className="summary-line"><span>Compras con saldo</span><b>{purchases.filter(r=>r.data.confirmation==='confirmed'&&r.data.paid<r.data.total).length}</b></div><div className="summary-line"><button className="secondary" onClick={()=>setView('Compras')}>Ver compras</button></div></section><section className="panel"><div className="panel-heading"><h2>Control de stock</h2></div><div className="summary-line"><span>Unidades por confirmar</span><b>{products.filter(p=>!p.data.unitConfirmed).length}</b></div><div className="summary-line"><span>Productos con stock negativo</span><b>{products.filter(p=>stock(p)<0).length}</b></div><div className="summary-line"><button className="secondary" onClick={()=>setView('Stock')}>Ver depósito</button></div></section></div></>}
 {['Compras','Stock','Pedidos','Reparto'].includes(view)&&<div className="toolbar"><input className="filter" aria-label="Buscar registros" placeholder={view==='Stock'?'Buscar producto…':'Buscar empresa, proveedor o producto…'} value={query} onChange={e=>setQuery(e.target.value)}/></div>}
 {view==='Compras'&&<><p className="section-description">El precio y el proveedor se conservan en cada ingreso. Los pagos posteriores reducen el saldo de esa compra.</p><section className="panel">{purchases.length?<DataTable headers={['Fecha / proveedor','Producto','Cantidad','Total / pagado','Estado / saldo','Acciones']}>{filtered(purchases).map(r=><TableRow key={r.id}><TableCell>{fmt(r.data.date)}<small>{r.data.supplier}<br/>{r.data.invoice||'Sin comprobante'}</small></TableCell><TableCell>{r.data.product}<small>{money(r.data.unitPrice)} por {r.data.unit}</small></TableCell><TableCell>{r.data.quantity} {r.data.unit}</TableCell><TableCell><b>{money(r.data.total)}</b><small>Pagado: {money(r.data.paid)}</small></TableCell><TableCell><span className={'tag '+(r.data.paid===r.data.total&&r.data.confirmation==='confirmed'?'green':'yellow')}>{status(r)}</span><small>Saldo: {money(r.data.total-r.data.paid)}</small></TableCell><TableCell><div className="table-actions">{r.data.confirmation==='pending'?<button disabled={saving} className="primary" onClick={()=>action({action:'confirmPurchase',id:r.id})}>Confirmar ingreso</button>:r.data.paid<r.data.total&&<button className="primary" onClick={()=>open('Registrar pago','payment',[dateField,num('amount','Monto a pagar ($)',.01,'.01')],{id:r.id,amount:(r.data.total-r.data.paid)/100},r.data.supplier+' · Saldo '+money(r.data.total-r.data.paid))}>Pagar</button>}<button className="secondary" onClick={()=>open('Detalle de compra','none',[],{},[r.data.note||'Sin observaciones.',...r.data.payments.map((p:any)=>fmt(p.date)+' · '+money(p.amount)+' · '+p.by)].join('\n'))}>Historial</button></div></TableCell></TableRow>)}</DataTable>:<Empty title="Todavía no hay compras" description="Registrá la mercadería recibida y cuánto se pagó al proveedor."/>}</section></>}
 {view==='Stock'&&<><p className="section-description">Disponible = ingresos confirmados + movimientos. Las cantidades del Excel son una referencia y requieren conteo físico. Las recetas descuentan ingredientes al preparar; otros consumos y pérdidas se cargan manualmente.</p>{!products.length&&role==='admin'&&<div className="notice"><span>Usá el catálogo del Excel para empezar.</span><button disabled={saving} className="primary" onClick={()=>action({action:'importCatalog'})}>Incorporar catálogo</button></div>}<section className="panel">{products.length?<DataTable headers={['Producto','Categoría','Disponible','Referencia Excel','Acciones']}>{filtered(products).sort((a,b)=>a.data.name.localeCompare(b.data.name)).map(p=><TableRow key={p.id}><TableCell><b>{p.data.name}</b><small>{p.data.unitConfirmed?p.data.unit:'Unidad por confirmar'}</small></TableCell><TableCell>{p.data.category}</TableCell><TableCell className={stock(p)<0?'stock-negative':''}>{p.data.unitConfirmed?Number(stock(p).toFixed(3)):'—'}</TableCell><TableCell>{p.data.referenceQty??'—'}<small>No incorporado al disponible</small></TableCell><TableCell>{p.data.unitConfirmed?<button className="secondary" onClick={()=>movementForm(p)}>Ingreso / consumo</button>:<button className="primary" onClick={()=>open('Confirmar unidad de registro','confirmUnit',[{key:'unit',label:'Unidad',options:pairs(units)}],{id:p.id,unit:'unidad'},p.data.name+'. Elegí cómo se contará y comprará este producto. Usá siempre esa misma unidad.')}>Confirmar unidad</button>}</TableCell></TableRow>)}</DataTable>:<Empty title="Sin productos" description={role==='bachero'?'Los productos de limpieza que cargues aparecerán acá.':'Incorporá el catálogo o registrá un producto nuevo.'}/>}</section></>}
 {view==='Pedidos'&&<section className="panel">{orderTable(filtered(orders))}</section>}
 {view==='Reparto'&&<><p className="section-description">Confirmá las cantidades despachadas antes de imprimir el remito. Al regresar, registrá lo recibido por la empresa.</p><section className="panel">{orderTable(filtered(orders.filter(r=>['preparado','enviado','entregado'].includes(r.data.status))))}</section></>}
 {view==='Empresas y proveedores'&&<div className="columns">{[['company','Empresas',companies],['supplier','Proveedores',suppliers]].map(([kind,label,list]:any)=><section className="panel" key={kind}><div className="panel-heading"><h2>{label}</h2><button className="primary" onClick={()=>entityForm(kind)}><Plus size={16}/>Agregar</button></div>{list.length?<DataTable headers={['Nombre','Contacto / dirección']}>{list.map((r:Row)=><TableRow key={r.id}><TableCell><b>{r.data.name}</b></TableCell><TableCell>{r.data.contact||'—'}<small>{r.data.address}</small></TableCell></TableRow>)}</DataTable>:<Empty title={'Sin '+label.toLowerCase()} description="Registrá el nombre y los datos de contacto."/>}</section>)}</div>}
 {view==='Platos y recetas'&&['admin','caja','cocina'].includes(role)&&<Recetas records={records} preparations={data.preparations||[]} role={role} onSaved={load}/>}
 {view==='Cuentas por cobrar'&&financial&&<Facturacion records={records} today={today} onSaved={load}/>}
 {view==='Equipo'&&<><div className="notice"><p>El rol se asigna por correo. El sitio es privado: registrar a un empleado acá no le concede acceso al sitio. Primero hay que habilitar el acceso del equipo.</p><button className="primary" onClick={()=>open('Asignar rol','member',[{key:'name',label:'Nombre'},{key:'email',label:'Correo de la cuenta',type:'email'},{key:'role',label:'Rol',options:Object.entries(roles)}],{role:'cocina'})}>Agregar trabajador</button></div><section className="panel"><DataTable headers={['Trabajador','Correo','Rol','Acciones']}>{data.members.map((m:any)=><TableRow key={m.email}><TableCell>{m.name}{m.owner?' · Propietario':''}</TableCell><TableCell>{m.email}</TableCell><TableCell><span className="tag">{roles[m.role]}</span></TableCell><TableCell><button className="secondary" onClick={()=>open('Modificar rol','member',[{key:'name',label:'Nombre'},{key:'email',label:'Correo',type:'email'},{key:'role',label:'Rol',options:m.owner?[['admin','Administración']]:Object.entries(roles)}],m)}>Modificar</button></TableCell></TableRow>)}</DataTable></section><p className="footer-note">Bachero: productos de limpieza y sus compras. Cocina: pedidos e insumos de cocina. Delivery: despacho, remitos y entregas. Caja y postres: compras, pedidos, postres y cierre. Administración: todas las funciones y permisos.</p></>}
 {view==='Cierre semanal'&&<><div className="toolbar"><label className="field">Semana desde<input type="date" value={week} onChange={e=>e.target.value&&setWeek(monday(e.target.value))}/></label><span>Hasta {fmt(weekEnd)}</span><button className="secondary" onClick={()=>doPrint({type:'weekly'})}><Printer size={17}/>Imprimir</button><button className="secondary" onClick={downloadCSV}><Download size={17}/>Descargar CSV</button></div><div className="metrics"><article><span>Viandas pedidas</span><strong>{sum(weekOrders,'quantity')}</strong><small>Semana seleccionada</small></article><article><span>Viandas entregadas</span><strong>{sum(weekOrders,'delivered')}</strong><small>Recibidas por las empresas</small></article><article><span>Compras confirmadas</span><strong>{money(confirmedWeek.reduce((a,r)=>a+r.data.total,0))}</strong><small>Pendientes: {money(weekPurchases.filter(r=>r.data.confirmation==='pending').reduce((a,r)=>a+r.data.total,0))}</small></article><article><span>Pagos realizados</span><strong>{money(weekPayments)}</strong><small>Por fecha de pago</small></article></div><section className="panel"><div className="panel-heading"><h2>Viandas por empresa</h2></div><DataTable headers={['Empresa','Pedidas','Preparadas','Enviadas','Entregadas','Postres recibidos','Diferencia envío / recepción']}>{companies.map(c=>{const rr=weekOrders.filter(r=>r.data.companyId===c.id);return <TableRow key={c.id}><TableCell>{c.data.name}</TableCell>{['quantity','prepared','sent','delivered','deliveredDesserts'].map(k=><TableCell key={k}>{sum(rr,k)}</TableCell>)}<TableCell>{sum(rr,'sent')-sum(rr,'delivered')}</TableCell></TableRow>})}</DataTable></section><section className="panel"><div className="panel-heading"><h2>Compras por proveedor</h2></div><DataTable headers={['Proveedor','Compras de la semana','Saldo de esas compras']}>{suppliers.map(s=>{const rr=confirmedWeek.filter(r=>r.data.supplierId===s.id);return <TableRow key={s.id}><TableCell>{s.data.name}</TableCell><TableCell>{money(rr.reduce((a,r)=>a+r.data.total,0))}</TableCell><TableCell>{money(rr.reduce((a,r)=>a+r.data.total-r.data.paid,0))}</TableCell></TableRow>})}</DataTable></section><p className="footer-note">Saldo total con proveedores a la fecha: {money(debt)}. La diferencia entre envío y recepción incluye entregas todavía sin confirmar. Las compras registradas no equivalen al costo de producción ni a la ganancia.</p></>}
 </>}
 </main></SidebarProvider><Dialog open={!!modal} onOpenChange={v=>{if(!saving&&!v)setModal(null)}}><DialogContent className="dialog-panel"><DialogHeader><DialogTitle>{modal?.title}</DialogTitle><DialogDescription>{modal?.note||'Completá los datos del registro.'}</DialogDescription></DialogHeader><form onSubmit={submit}><div className="form-grid">{modal?.fields.map(f=><FieldInput key={f.key} field={f} value={form[f.key]} change={v=>setForm((old:any)=>({...old,[f.key]:v,...(f.key==='confirmation'&&v==='pending'?{paid:0}:{})}))}/>)}</div>{form.action==='progress'&&form.status==='preparado'&&<div className="notice" style={{display:'block',marginTop:16}}><b>Consumo al guardar</b>{preparationPreview().length?preparationPreview().map((i:any,n:number)=>{const p=products.find(p=>p.id===i.productId);return <p key={n} className="form-note">{i.product}: {i.quantity} {i.stockUnit}{p&&stock(p)<i.quantity?' · Stock insuficiente; quedará negativo':''}</p>}):<p className="form-note">Sin receta vinculada o sin porciones: no se descontarán ingredientes automáticamente. Los consumos sin receta deben cargarse en Stock.</p>}</div>}{form.action==='purchase'&&<p className="currency-preview">Total: {money(Math.round(Number(form.quantity||0)*Math.round(Number(form.unitPrice||0)*100)))}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setModal(null)}>Cerrar</button>{form.action!=='none'&&<button className="primary" disabled={saving||modal?.fields.some(f=>f.required!==false&&f.options&&!form[f.key])} type="submit">{saving?'Guardando…':'Guardar'}</button>}</div></form></DialogContent></Dialog>
 {print&&typeof document!=='undefined'&&createPortal(<div className="print-document"><header><div><h1>La Cocina del Bondi</h1><p>{print.type==='remito'?'REMITO DE ENTREGA':'CIERRE SEMANAL'}</p></div><img src="/logo.png" alt="La Cocina del Bondi"/></header>{print.type==='remito'?<><p><b>Remito N.º {String(print.order.id).padStart(6,'0')}</b> · Fecha: {fmt(print.order.data.date)}</p><p><b>Empresa:</b> {print.order.data.company}</p><p><b>Dirección:</b> {print.order.data.address||'____________________________'}</p><p><b>Repartidor:</b> {print.order.data.driver}</p><table><thead><tr><th>Detalle</th><th>Cantidad enviada</th></tr></thead><tbody><tr><td>Viandas · {print.order.data.menu}</td><td>{print.order.data.sent}</td></tr><tr><td>Postres</td><td>{print.order.data.sentDesserts}</td></tr></tbody></table><p>Observaciones: {print.order.data.note||'_____________________________________'}</p>{print.order.data.status==='entregado'&&<p>Recibidas: {print.order.data.delivered} viandas y {print.order.data.deliveredDesserts} postres. Recibió: {print.order.data.receiver}. {print.order.data.deliveryNote}</p>}<div className="signatures"><p>Firma / aclaración de quien recibe</p><p>Firma del repartidor</p></div><p style={{marginTop:35,fontSize:12}}>Comprobante de entrega. No válido como factura.</p></>:<><p>{fmt(week)} al {fmt(weekEnd)}</p><table><thead><tr><th>Empresa</th><th>Pedidas</th><th>Enviadas</th><th>Entregadas</th><th>Postres</th></tr></thead><tbody>{companies.map(c=>{const rr=weekOrders.filter(r=>r.data.companyId===c.id);return <tr key={c.id}><td>{c.data.name}</td>{['quantity','sent','delivered','deliveredDesserts'].map(k=><td key={k}>{sum(rr,k)}</td>)}</tr>})}</tbody></table><p>Compras confirmadas de la semana: {money(confirmedWeek.reduce((a,r)=>a+r.data.total,0))}</p><p>Pagos realizados en la semana: {money(weekPayments)}</p><p>Saldo total con proveedores a la fecha: {money(debt)}</p><p>Viandas pedidas: {sum(weekOrders,'quantity')} · Entregadas: {sum(weekOrders,'delivered')}</p></>}</div>,document.body)}
 </>;
}
