// Transcribed from the two recipe references. Ambiguous source units remain
// blank and must be confirmed before a usable recipe can be saved.
type Ingredient={product:string;quantity:number;unit:string;note?:string;trackStock?:boolean};
export type RecipeTemplate={key:string;name:string;category:string;code:string;sourceLabel:string;portions:number;yieldLabel:string;portionWeight?:number;durationMinutes?:number;ingredients:Ingredient[];instructions:string;note:string};
const ingredient=(product:string,quantity:number,unit:string,note=''):Ingredient=>({product,quantity,unit,note});
export function malfattisTemplate(portions:number):RecipeTemplate{
 const variants:Record<number,{minutes:number;items:Ingredient[]}>={
  15:{minutes:120,items:[ingredient('Ricota',3,'kg'),ingredient('Sal',55,'g'),ingredient('Nuez moscada',3,'g'),ingredient('Pimienta',1,'g'),ingredient('Queso para rallar',600,'g','Queso bueno rallado fino'),ingredient('Huevos',3,'unidad','Huevos grandes'),ingredient('Harina',1.1,'kg'),ingredient('Espinaca',600,'g','Peso de espinaca blanqueada: revisar merma antes de vincular con espinaca cruda')]},
  20:{minutes:150,items:[ingredient('Ricota',4,'kg'),ingredient('Sal',75,'g'),ingredient('Nuez moscada',4,'g'),ingredient('Pimienta',2,'g'),ingredient('Queso para rallar',800,'g','Queso bueno rallado fino'),ingredient('Huevos',4,'unidad','Huevos grandes'),ingredient('Harina',1.45,'kg'),ingredient('Espinaca',800,'g','Peso de espinaca blanqueada: revisar merma antes de vincular con espinaca cruda')]},
  25:{minutes:180,items:[ingredient('Ricota',5,'kg'),ingredient('Sal',95,'g'),ingredient('Nuez moscada',5,'','El documento no indica la unidad'),ingredient('Pimienta',2,'','El documento no indica la unidad'),ingredient('Queso para rallar',1,'kg','Queso bueno rallado fino'),ingredient('Huevos',5,'unidad','Huevos grandes'),ingredient('Harina',1.8,'kg'),ingredient('Espinaca',1,'kg','Espinaca blanqueada, casi una jaula; revisar merma y presentación del depósito')]},
  30:{minutes:210,items:[ingredient('Ricota',6,'kg'),ingredient('Sal',110,'g'),ingredient('Nuez moscada',6,'','El documento no indica la unidad'),ingredient('Pimienta',3,'','El documento no indica la unidad'),ingredient('Queso para rallar',1.2,'','El documento indica «1.200» sin unidad; confirmar'),ingredient('Huevos',7,'unidad'),ingredient('Harina',2.2,'','El documento indica «2.2» sin unidad; confirmar'),ingredient('Espinaca',1.2,'','El documento indica «1.200» blanqueada (1 jaula), sin unidad; confirmar')]},
 };
 const v=variants[portions];if(!v)throw new Error('Rendimiento de Malfattis inválido');
 return {key:'malfattis-'+portions,name:'Malfattis · '+portions+' porciones',category:'Pastas',code:'2',sourceLabel:'2 Malfattis.docx',portions,yieldLabel:'porciones',...(portions>=25?{portionWeight:300}:{}),durationMinutes:v.minutes,ingredients:v.items,instructions:'',note:'Cantidades de la variante de '+portions+' porciones del documento. Las variantes no son idénticas a un escalado proporcional: elegí la ficha base adecuada. La elaboración no está detallada en el archivo. La espinaca se pesa blanqueada; ajustá la cantidad o equivalencia si el depósito registra materia prima cruda.'};
}
export function salvadoTemplate(yieldType:string,winter:boolean):RecipeTemplate{
 const yields:Record<string,[number,number]>={calzonis:[40,180],piadinas:[85,90],bollitos:[150,50]};const v=yields[yieldType];if(!v)throw new Error('Rendimiento de pan inválido');
 return {key:'salvado-'+yieldType+(winter?'-invierno':''),name:'Pan de salvado · '+yieldType+(winter?' · invierno':''),category:'Masas',code:'7',sourceLabel:'7 Pan de Salvado.docx',portions:v[0],yieldLabel:yieldType,portionWeight:v[1],ingredients:[ingredient('Salvado',500,'g','Hidratar en 1 litro de agua'),{...ingredient('Agua',3,'litro','1 litro para hidratar el salvado y 2 litros adicionales'),trackStock:false},ingredient('Harina',4,'kg'),ingredient('Sal',80,'g'),ingredient('Azúcar',100,'g','Preferentemente rubia o negra'),ingredient('Levadura',winter?100:50,'g',winter?'Cantidad de invierno':'Cantidad habitual'),ingredient('Aceite',100,'ml','100 cc equivalen a 100 ml')],instructions:'1. Hidratar el salvado. Disolver la levadura con una cucharada de harina, otra de azúcar y un chorrito de agua tibia.\n2. Colocar los secos restantes en la amasadora.\n3. Cuando la levadura active, agregarla e incorporar el líquido restante con la amasadora encendida.\n4. A los 5 minutos, cuando se unan los ingredientes, agregar la materia grasa y amasar 5 minutos más. Apagar.\n5. Pasar a una batea, cubrir con film y dejar descansar.\n6. Formar piezas del tamaño elegido y dejar descansar antes de hornear según su tamaño.',note:'Se puede acelerar el proceso con agua tibia o usar agua fría y dejar descansar 24 horas en heladera. El archivo no especifica temperatura ni tiempo de horno. Extracto de malta opcional: sin cantidad indicada, no se incorpora al descuento. Agua sin control de depósito por defecto; se puede vincular a un producto si se controla. Las cucharadas y el chorrito para activar la levadura se consideran parte de los ingredientes base: revisar si se usan cantidades adicionales.'};
}
